-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 21:38:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema min-url
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema min-url
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `min-url` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `min-url` ;

-- -----------------------------------------------------
-- Table `min-url`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `min-url`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `id_user_hash` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `google_id` VARCHAR(255) NULL DEFAULT NULL,
  `microsoft_id` VARCHAR(255) NULL DEFAULT NULL,
  `provider` ENUM('email', 'google', 'microsoft') NULL DEFAULT NULL,
  `profile_picture` TEXT NULL DEFAULT NULL,
  `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `iduser_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `iduserkey_UNIQUE` (`id_user_hash` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `min-url`.`urls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `min-url`.`urls` (
  `id_url` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NULL DEFAULT NULL,
  `id_url_hash` VARCHAR(64) NULL DEFAULT NULL,
  `longurl` TEXT NOT NULL,
  `shorturl` VARCHAR(16) NOT NULL,
  `clicks` INT UNSIGNED NOT NULL DEFAULT 0,
  `ip_address` VARCHAR(32) NOT NULL,
  `country` VARCHAR(10) NULL DEFAULT NULL,
  `region` VARCHAR(16) NULL DEFAULT NULL,
  `timezone` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` VARCHAR(255) NULL DEFAULT NULL,
  `longitude` VARCHAR(255) NULL DEFAULT NULL,
  `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_url`),
  INDEX `fk_url_user_idx` (`user_id_user` ASC) VISIBLE,
  UNIQUE INDEX `id_url_key_UNIQUE` (`id_url_hash` ASC) VISIBLE,
  UNIQUE INDEX `shorturl_UNIQUE` (`shorturl` ASC) VISIBLE,
  CONSTRAINT `fk_url_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `min-url`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `min-url`.`logurls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `min-url`.`logurls` (
  `id_logurl` INT NOT NULL AUTO_INCREMENT,
  `url_id_url` INT NOT NULL,
  `id_logurl_hash` VARCHAR(64) NULL DEFAULT NULL,
  `ip_address` VARCHAR(32) NOT NULL,
  `country` VARCHAR(10) NULL DEFAULT NULL,
  `region` VARCHAR(16) NULL DEFAULT NULL,
  `timezone` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` VARCHAR(255) NULL DEFAULT NULL,
  `longitude` VARCHAR(255) NULL DEFAULT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_logurl`),
  UNIQUE INDEX `idlogurl_UNIQUE` (`id_logurl` ASC) VISIBLE,
  INDEX `fk_logurl_url1_idx` (`url_id_url` ASC) VISIBLE,
  UNIQUE INDEX `idlogurlkey_UNIQUE` (`id_logurl_hash` ASC) VISIBLE,
  CONSTRAINT `fk_logurl_url1`
    FOREIGN KEY (`url_id_url`)
    REFERENCES `min-url`.`urls` (`id_url`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
